app:
  github-token: ${GITHUB_TOKEN}

  stackoverflow:
    key: ${SO_TOKEN_KEY}
    access-token: ${SO_ACCESS_TOKEN}

  fixed-rate-string: 5000 # in milliseconds
  batch-size: 500

spring:
  application:
    name: Scrapper

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgresql:5432/scrapper
    username: postgres
    password: postgres

  liquibase:
    enabled: false

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.format_sql: true
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

server:
  port: 8081

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui

github:
  base-url: https://api.github.com

stackoverflow:
  base-url: https://api.stackexchange.com/2.3

bot:
  url: http://bot:8080
