global:
  scrape_interval: 30s

scrape_configs:
  - job_name: 'bot'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['bot:9080']

  - job_name: 'scrapper'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['scrapper:9081']
