{
 "title": "Custom",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "ScrapeByType",
   "type": "timeseries",
   "description": "Operating time of one scrape by type",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(scrape_duration_seconds_bucket{type=\"GITHUB\"}[24h])) by (le))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(scrape_duration_seconds_bucket{type=\"STACK_OVERFLOW\"}[24h])) by (le))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(scrape_duration_seconds_bucket{type=\"GITHUB\"}[24h])) by (le))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(scrape_duration_seconds_bucket{type=\"STACK_OVERFLOW\"}[24h])) by (le))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(scrape_duration_seconds_bucket{type=\"GITHUB\"}[24h])) by (le))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(scrape_duration_seconds_bucket{type=\"STACK_OVERFLOW\"}[24h])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "LinksByType",
   "type": "timeseries",
   "description": "Number of active links in the database by type",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "active_links_by_type", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "MpS",
   "type": "timeseries",
   "description": "Number of user messages per second",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "rate(user_messages_total[1m])", "legendFormat": "__auto" }
   ]
  }
 ]
}