{
 "title": "REDM",
 "time": { "from": "2025-05-13T10:25:19.026Z", "to": "2025-05-13T13:37:16.595Z" },
 "templating": {
  "list": [
   { "name": "app" }
  ]
 },
 "panels": [
  {
   "title": "Rate (R)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{job=\"$app\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors (E)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{job=\"$app\", status=~\"4..\", status=~\"4..|5..\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Duration (D)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_sum{job=\"$app\"}[1m]) / rate(http_server_requests_seconds_count{job=\"$app\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory (M)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by (id, area) (jvm_memory_used_bytes{job=\"$app\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}