app:
  telegram-token: ${TELEGRAM_TOKEN}
  n-threads: 2

  notifications:
    topic: notifications
    group-id: consumer-group

spring:
  application:
    name: Bot

  liquibase:
    enabled: false

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

server:
  port: 8080

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui

scrapper:
  url: http://scrapper:8081
