app:
  telegram-token: ${TELEGRAM_TOKEN}
  n-threads: 2

  notifications:
    topic: notifications
    dlq: dlq
    group-id: consumer-group

spring:
  application:
    name: Bot

  liquibase:
    enabled: false

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  kafka:
    bootstrap-servers: kafka-1:9092, kafka-2:9092

  data:
    redis:
      host: redis
      port: 6379

server:
  port: 8080

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui

scrapper:
  url: http://scrapper:8081

  timeouts-in-sec:
    connect: 1
    connection-request: 2
    read: 2

retry:
  back-off-period: 2000 # in ms
  max-attempts: 2
  retryable-statuses:
    - 500
    - 502
    - 503

rate-limiting:
  max-requests-per-minute: 5

resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 5
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 1
    instances:
      scrapper-client:
        baseConfig: default

management:
  server:
    port: 9080
  endpoints:
    web:
      base-path: "/"
      path-mapping:
        prometheus: "metrics"
      exposure:
        include:
          - prometheus
